I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 64, in script
    $ preparedness -= 15
  File "game/script.rpy", line 64, in <module>
    $ preparedness -= 15
NameError: name 'preparedness' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 64, in script
    $ preparedness -= 15
  File "C:\Users\alice\Downloads\renpy-8.3.2-sdk\renpy-8.3.2-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\alice\Downloads\renpy-8.3.2-sdk\renpy-8.3.2-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 64, in <module>
    $ preparedness -= 15
NameError: name 'preparedness' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
JAPN 300 Final Project 1.0
Wed Nov  6 14:17:48 2024
